//POSTS 

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Some title53",
    "content": "some content534",
    "userID": "1"
}

###
get http://localhost:3000/posts

###
get http://localhost:3000/posts/12
###
DELETE http://localhost:3000/posts/14
###
PUT  http://localhost:3000/posts/13
Content-Type: application/json

{
    "title": "updated",
    "content":"u content"
}
###
//LIKES
POST http://localhost:3000/posts/like/12
Content-Type: application/json

{
    "userID":"1"
}
###
//COMMENTS
POST http://localhost:3000/posts/comment/12
Content-Type: application/json

{
    "text":"this is sendond comment for post 12 user id 1",
    "userID":"1"
}



###
//USERS
POST  http://localhost:3000/sign-in
Content-Type: application/json

{
    "email": "darko@gmail.com",
    "username": "Veljko ",
    "password":"nekaLozinka123"
}

###

POST  http://localhost:3000/log-in
Content-Type: application/json

{
    "email": "darko@gmail.com",
    "password":"nekaLozinka123"
}