//POSTS 

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Some title53",
    "content": "some content534",
    "userID": "1"
}

###
get http://localhost:3000/posts

###
get http://localhost:3000/posts/12
###
DELETE http://localhost:3000/posts/14
###
PUT  http://localhost:3000/posts/13
Content-Type: application/json

{
    "title": "updated",
    "content":"u content"
}
###
//LIKES
POST http://localhost:3000/posts/like/12
Content-Type: application/json

{
    "userID":"1"
}
###
//COMMENTS
POST http://localhost:3000/posts/comment/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJ1c2VyX25hbWUiOiJWZWxqa28gIiwiZ29vZ2xlX2lkIjpudWxsLCJlbWFpbCI6ImRhcmtvQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwicGFzc3dvcmRfaGFzaCI6IiQyYSQxMCRacXRWVmN4U3M0Y3h4cU4xbDZwN1V1R3NGV1liNlF3QnNONmlNYmZjcndyQVRaLnFNWHFkSyJ9LCJpYXQiOjE3MzcxMjk0MTQsImV4cCI6MTczNzIxNTgxNH0.Ab6c2xglq8uSYGDpERbUxl7kTbfjiF39lX32bLv26ew
Content-Type: application/json

{
    "text":"this is sendond fdas for post 12 user id 1",
    "userID":"1"
}



###
//USERS
POST  http://localhost:3000/sign-in
Content-Type: application/json

{
    "email": "marko@gmail.com",
    "username": "marko ",
    "password":"nekaLozinka123"
}

###

POST  http://localhost:3000/log-in
Content-Type: application/json

{
    "email": "darko@gmail.com",
    "password":"nekaLozinka123"
}

###
GET  http://localhost:3000/log-in/protected-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJ1c2VyX25hbWUiOiJWZWxqa28gIiwiZ29vZ2xlX2lkIjpudWxsLCJlbWFpbCI6ImRhcmtvQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwicGFzc3dvcmRfaGFzaCI6IiQyYSQxMCRacXRWVmN4U3M0Y3h4cU4xbDZwN1V1R3NGV1liNlF3QnNONmlNYmZjcndyQVRaLnFNWHFkSyJ9LCJpYXQiOjE3MzcxMjk0MTQsImV4cCI6MTczNzIxNTgxNH0.Ab6c2xglq8uSYGDpERbUxl7kTbfjiF39lX32bLv26ew

###
